#!/bin/bash
#MSUB -d /g/g90/aravind/scratch/src/sst-elements-library-6.0.0/src/sst/elements/behavioralEmulation/tests
#MSUB -N be_sim-es9ec64np16384.job
#MSUB -l nodes=2
#MSUB -l partition=cab
#MSUB -q pbatch
#MSUB -l walltime=01:30:00
#MSUB -o check-d/bonebe-es9ec64np16384.csv
#MSUB -e check-d/err/be_sim-es9ec64np16384.err
 
module load gnu/4.9.2 openmpi-gnu/1.8
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32"
export BOOST_HOME=$HOME/local/packages/boost-1.56
export LD_LIBRARY_PATH=$BOOST_HOME/lib:$LD_LIBRARY_PATH
export SST_CORE_HOME=$HOME/local/sst-core-6.0
export PATH=$SST_CORE_HOME/bin:$PATH
export SST_ELEMENTS_HOME=$HOME/local/sst-elements-6.0
export PATH=$SST_ELEMENTS_HOME/bin:$PATH
 
./BE_RUN.sh -c vulcan-proper-es9ec64np16384.py -n 32
