#!/bin/bash
##### These lines are for Moab
#MSUB -d /g/g90/aravind/scratch/src/sst-elements-library-6.0.0/src/sst/elements/behavioralEmulation/tests
#MSUB -N test-be.job
#MSUB -l nodes=1
#MSUB -l partition=cab
#MSUB -q pbatch
#MSUB -l walltime=00:20:00
#MSUB -o be-test.csv
#MSUB -e be-test.err

module load gnu/4.9.2 openmpi-gnu/1.8
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32"
export BOOST_HOME=$HOME/local/packages/boost-1.56
export LD_LIBRARY_PATH=$BOOST_HOME/lib:$LD_LIBRARY_PATH
export SST_CORE_HOME=$HOME/local/sst-core-6.0
export PATH=$SST_CORE_HOME/bin:$PATH
export SST_ELEMENTS_HOME=$HOME/local/sst-elements-6.0
export PATH=$SST_ELEMENTS_HOME/bin:$PATH

#echo "--------------------- CHECKs -------------------------"
#echo $PATH
#echo $LD_LIBRARY_PATH
#mpirun sst --version
#echo "---------------------- END ----------------------------"

./BE_RUN.sh -c vulcan-proper.py -n 1 -v
